name: lattes
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster
  - asn1crypto
  - atomicwrites
  - attrs
  - babel
  - backcall
  - backports
  - bleach
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - chardet
  - configparser
  - cryptography
  - cycler
  - cython
  - dbus
  - decorator
  - defusedxml
  - docutils
  - entrypoints
  - expat
  - extinction
  - fontconfig
  - freetype
  - fribidi
  - future
  - gettext
  - graphite2
  - graphviz
  - gst-plugins-base
  - gstreamer
  - harfbuzz
  - icu
  - idna
  - imagesize
  - iminuit
  - importlib_metadata
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - jupyter_core
  - jupyter_highlight_selected_word
  - jupyter_latex_envs
  - jupyter_nbextensions_configurator
  - jupyterthemes
  - kiwisolver
  - kombine
  - libpng
  - lxml
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mistune
  - nb_conda_kernels
  - nbconvert
  - nbformat
  - ncurses
  - notebook
  - nspr
  - nss
  - numpy
  - numpydoc
  - olefile
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - pango
  - parso
  - pcre
  - pexpect
  - pillow
  - pip
  - pixman
  - pluggy
  - ply
  - prometheus_client
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - py
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - pytest
  - pytest-arraydiff
  - pytest-doctestplus
  - pytest-openfiles
  - pytest-remotedata
  - pytest-runner
  - python
  - python-dateutil
  - pytz
  - pyyaml
  - pyzmq
  - qt
  - qtconsole
  - qtpy
  - readline
  - requests
  - schwimmbad
  - scikit-learn
  - scipy
  - send2trash
  - setuptools
  - sip
  - six
  - snowballstemmer
  - sphinx
  - sphinx-automodapi
  - sphinx-gallery
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sqlite
  - terminado
  - testpath
  - tk
  - tornado
  - tqdm
  - traitlets
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxpm
  - xorg-libxrender
  - xorg-libxt
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - seaborn
